set-option -g mouse on              # pour activer la souris si tu veux en plus
# (ancien) bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -i"
set-window-option -g mode-keys vi
# Couleur de la barre
set-option -g status-bg colour22   # fond vert foncé
set-option -g status-fg white      # texte en blanc

set -g set-titles on
set -g set-titles-string '#T'


# --- Copier/coller simplifié ---
# Sélection à la souris = copie automatique dans le presse-papier (Wayland)
set -s set-clipboard on
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode    MouseDragEnd1Pane send -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"
# Double-clic = copie le mot, triple-clic = copie la ligne
bind-key -T root DoubleClick1Pane select-pane \; copy-mode -M \; send -X select-word \; run -d0.3 \; send -X copy-pipe-and-cancel "wl-copy"
bind-key -T root TripleClick1Pane select-pane \; copy-mode -M \; send -X select-line \; run -d0.3 \; send -X copy-pipe-and-cancel "wl-copy"
