# 3 doigts gauche/droite = changer d'espace de travail
gesture swipe right	4	swaymsg workspace next
gesture swipe left	4	swaymsg workspace prev

# 4 doigts gauche/droite = changer de fenêtre
gesture swipe left	3	swaymsg focus left
gesture swipe right	3	swaymsg focus right
